Food_quantity = 100
Speed = 3 #min 1 max 10
Size = 3 #min 1 max 10
View = 3 #min 1 max 10
Speed_variation = 15 #min 1 max 500, pourcentage
Size_variation = 15 #min 1 max 500, pourcentage
View_variation = 15 #min 1 max 500, pourcentage
Days_max = 10 #min 1 max 1000
Simulation_duration = 1 #min 1 max 10000, en jours
Color = 'white' #white, red, green, blue, yellow, cyan, magenta, black
Button_font = 'arial' #nom de la police d'écriture pour les boutons
Display_size = (800, 600) #taille de la fenêtre d'affichage (largeur, hauteur)